apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: cicd-demo
